---
driver:
  name: docker
  use_sudo: false
platforms:
  - name: ubuntu-14.04
provisioner:
  name: chef_zero
suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[smoke]
