---
driver:
  name: docker
  use_sudo: false
platforms:
  - name: ubuntu-14.04-chef-11
    driver_config:
      image: ubuntu:14.04
      require_chef_omnibus: 11.18.12
  - name: ubuntu-14.04-chef-12
    driver_config:
      image: ubuntu:14.04
      require_chef_omnibus: 12.5.1
provisioner:
  name: chef_zero
suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[smoke]
