name             'chef_bundle'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
license          'Apache 2.0'
description      'Provides Bundler for Chef'
long_description 'Provices Bundler for Chef'
version          '0.4.0'
